### ISSUE TITLE
Add curated link for "Constructive Code Critique"

### ISSUE THREAD

**Issue by maherou** [betterscientificsoftware/betterscientificsoftware.github.io#129]
The link is: https://www.software.ac.uk/blog/2017-05-11-constructive-code-critique?utm_source=Weekly+newsletter+list&utm_campaign=0e3fccba85-RSS_EMAIL_CAMPAIGN&utm_medium=email&utm_term=0_009a7f1607-0e3fccba85-116856489

**Comment by bernhold** [comment]
FYI, that link can safely be shortened to

https://www.software.ac.uk/blog/2017-05-11-constructive-code-critique

Everything after this is done for tracking purposes.

**Comment by pagrubel** [comment]
From David: maybe we would add Jeff Carver's peer code-review tutorial and other resources.

**Comment by markcmiller86** [comment]
Not picking on @pagrubel because I see others doing this but we should all be getting into the practice of using @-mentions for people's names instead of just their textual name. So, instead of...

> From David: maybe we would add Jeff Carver's peer code-review tutorial and other resources.

we have...

 From @bernhold : maybe we would add Jeff Carver's peer code-review tutorial and other resources.

I don't have Jeff Carver's github handle or I would have used it.

**Comment by bernhold** [comment]
I would say that @-mentioning EB members is fine, but does it confer any real benefits?

I would say that @-mentioning others in this situation is probably *not* desirable. We're not seeking their input (at this time) and I don't think we really want to expose this conversation to then. (I know it is public and they could find it if they wanted to. But that seems unlikely.)
________________________________

**Comment by rinkug** [comment]
This issue was completed and published
