### ISSUE TITLE
Google Form suggestions

### ISSUE THREAD

**Issue by pagrubel** [betterscientificsoftware/betterscientificsoftware.github.io#278]
The form was easy to follow except I miss answering one of the questions and got stuck. Suggestions (not sure if these are all feasible):
1. It would be nice if there was a way to either save the form to come back to or at least a shortcut for someone who has already read the requirements etc. I know you want them to read it all, but I had interruptions and also just read through it before I even got started. So after I wrote my article offline, I would have liked to find a link to go to the submission. I believe the guidlines are in there also. 

2. Put Choose for those questions in red. I missed one of them and didn't even see the red *. I think my eyes focused on the blue link. Just a suggestion.

3. The button at the top for contribution was hard to find intially, but I did find it. Maybe it should be on the second line in blue (up to you).

The process was easy and most of the above is minor, but @curfman asked for input, so here it is.

**Comment by maherou** [comment]
@pagrubel, Thanks for the feedback.  Unfortunately, these suggestions are not actionable without switching to a different tools.  The look-and-feel of Google Forms limits what we can do with formatting and similar issues.  I will close the issue since we don't have plans to switch away from Google Forms at this time.
