### ISSUE TITLE
Possible article on self-perceptions

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/betterscientificsoftware.github.io#348]
Author: Rinku Gupta
EB member: Pat G.

Carver, J., D. Heaton, L. Hochstein, and R. Bartlett. [“Self-Perceptions about Software Engineering: A Survey of Scientists and Engineers.”](https://www.computer.org/csdl/mags/cs/2013/01/mcs2013010007.pdf) Computing in Science Engineering 15, no. 1 (January–February 2013): 7–11.

I think this could make a great curated content article. 

I haven't read it in detail but have heard others say good things about it.

- [x] First favorable review
- [x] Second favorable review

**Comment by rinkug** [comment]
- This is a pretty good article on our immediate community and how the view SE

- The trends we see in the paper are very consistent with what I have experienced (i.e projects do  have informally-learned familiarity with version control, documentations systems, validation/verification and less with code reviews/agile methods etc..even for production code)

- Good additional for our curated content

- Recommend combining it with "Basili, V. et al., Understanding the high-performance-computing community: A software engineer's perspective, IEEE Software, 25, 2008"

- Need intro summary to be added in "curated item description" before  posting this online so that audience has a good idea of what the paper contains and why it may be relevant

**Comment by rinkug** [comment]
Consider Rinku as author  and Pat as EB board member. Timeline TBD? Due in september to be published end of september.

**Comment by rinkug** [comment]
Continued discussion will occur in the PR #428 for this journal article, which is to become curated content
