### ISSUE TITLE
Possible Curated Content Scrum is Dead

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/betterscientificsoftware.github.io#352]
This suggestion for a curated content article comes from Jason Gates via the BSSw contact form.  I asked if he wants to write it up, but he said there's too much red tape in his organization to make it worth the effort.  So I assured him that we'd take it from here.  So I think this can be fodder for working out our workflow .

The suggestion: 

This was an interesting article I came across earlier this week.

Scrum is dead: Breaking down the new open development method

https://opensource.com/business/15/11/open-development-method

- [ ] First favorable review
- [ ] Second favorable review

**Comment by markcmiller86** [comment]
I gave the article a full read. Its interesting. It is 3.5 years old at this point. I am not sure Scrum has died? I have some friends in commercial sector and one has worked at two different Si-Valley software firms; both use Scrum today even with distributed development teams (e.g. some in India). The logistics for world-wide distributed teams are problematic due to time-zone diffs but they seem to cope. I think the Scrum paradigm has merit for certain projects.

I wonder about relevance of the main argument, Scrum is dead, to HPC/CSE code teams too. I don't know many HPC/CSE projects using Scrum who would care. I've advocated for VisIt to use Scrum but that hasn't happened partly because there are few full-time developers on VisIt. We are all split among several projects and, as the article alluedes to,  Scrum can force inconvenient sync. points.

I thought the comparison and contrast with Open development model was interesting and useful. The tenets of Open development, as a list of virtues, are good too. However, some of these topical areas, Asynchronicity, Democracy, Discussion, have some pitfalls too which aren't mentioned here.

I'm on the fence. There is no thumb-sideways emojii ;) I would have liked the article more if it identified the strenghts and weaknesses of each development paradigm.

**Comment by pagrubel** [comment]
I just have a comment about our procedure here. I think the title of this should be a bit more informative, afterall we have a tag for curated content that implies possible.

**Comment by pagrubel** [comment]
I also read the article and agree the the comparison between Open development model and Scrum is interesting but I'm not that enthusiastic about the article for this site. So agree with Mark. Lets decide today.

**Comment by rinkug** [comment]
Not enough interest?

**Comment by prwolfe** [comment]
I read through the article and visited the comments and the GitHub site the author had set up to collect discussion. I agree with Mark that at 3.5 years old (and with little or no follow up) the method is in no way ready to replace scrum.  In my mind he is also comparing two orthogonal ideas.  As one commenter said

> You're comparing a methodology that focuses on customer value to one that focus on code quality.

which leaves me with the question, why not take a more reconcilable attitude towards scrum rather than this confrontational one. I recommend against this article.

**Comment by pagrubel** [comment]
I gave this a thumbs down I don't think it can stand by itself. It would be nice if Jason could write a blog article, he could point to this if he wants and other sources. I just felt this was not what I was looking for as helpful.

**Comment by markcmiller86** [comment]
FWIW...I think we have sufficient dialog here to close this issue and label as `no-interest` as per our workflow/policies.

**Comment by bartlettroscoe** [comment]
Was not a big fan of this blog article.
