### ISSUE TITLE
Container Mythbusters

### ISSUE THREAD

**Issue by pagrubel** [betterscientificsoftware/betterscientificsoftware.github.io#401]
Authors: Pat Grubel (from the notes below).
EB member: Ross

Container Mythbusters is a you tube video by Michael Jennings of Los Alamos, that discusses a number of misconceptions about containers and container runtimes for HPC
It points out Charliecloud, developed at LANL and the security advantages of the user namespace.
https://www.youtube.com/watch?v=FFyXdgWXD3A&feature=youtu.be

Using containers on HPC resources is becoming an important way to build user software stacks. It is not easy to deploy them. This video helps with understanding what can be done.

**Comment by pagrubel** [comment]
@bartlettroscoe I assigned you mentioned (a while back ) that you would review the video

**Comment by bartlettroscoe** [comment]
Okay, I will have a look.

**Comment by pagrubel** [comment]
@bartlettroscoe I just saw Michael and this may not be the most current video so I'm checking with him on that and will let you know. I just didn't want you wasting cycles, so please wait. I don't think too much of the content has changed.

**Comment by bartlettroscoe** [comment]
>  I just saw Michael and this may not be the most current video so I'm checking with him on that and will let you know. I just didn't want you wasting cycles, so please wait. 

Okay.  Let me know.

**Comment by pagrubel** [comment]
@bartlettroscoe Here's the newer video link
https://youtu.be/H6VrjowOOF4

**Comment by bartlettroscoe** [comment]
Thanks @pagrubel, I am watching it now and will take some notes.

**Comment by rinkug** [comment]
Ross volunteered to write a cc for this

**Comment by pagrubel** [comment]
I was thinking of writing something so will instead marshall this.

**Comment by bartlettroscoe** [comment]
I watched this talk a couple of weeks ago and below I give my notes and recommendations.

----

Summary of the talk:
* What is a “Container”?  How it is defined?
  * 1) A process running on a system that provides a customized view of the system (this is the most correct definition of the term “Container”)
  * 2) A stack of images that can be run as a container process (e.g. like a Docker repository of container images)
  * People will sometimes use these terms interchangeably
* Containers are not a prefect security boundary
* Containers are ways to basically lie to your child processes about the system they are running on by using Linux kernel namespaces (a different file-system and directories, different host-name and domain-name, different network settings IP, etc., limits on amount of disk and memory that can be used which are enforced at the kernel level).
* Containers couple applications to their OS env
* Docker made a mistake => They did not take security and providence seriously
  * => That lead everyone-but-Docker who cared about containers (e.g. Google, Facebook, etc.) to form the Open Container Initiative to do their own thing.
* Docker did not care about HPC so that lead to HPC-specific efforts like Shifter, Charliecloud
  * Shifter …
  * Charliecloud is based on unprivileged Linux kernel namespaces and can be installed by any user and runs on RHEL7+ (not RHEL6) and many other linux distributions.
	Developed at LANL (where ??? is form)
  * Singularity is most widely used for HPC but has had 17+ CVE (security incidences) from 2016-2018
  * Podman is a drop-in replacement for docker (same commandline) that can work for HPC
* You can create your own container in bash with basic linux functions
* LANL is looking at Podman as a way to replace Charliecloud.

Summary of my analysis:
* Very good talk.  Michel Jennings is a very good speaker.
* Provides a good summary of the foundation for container technology from the basics linux kernel functions that support it, the different approaches to creating containers (i.e. privileged/setuid approaches vs. unprivileged namespaces, process running on a Linus system that like to the programs/processes that run under that process, etc.). This seems like it would be valid and useful for many years to come.
* There is also some good history about containers, from early attempts with chroot() to Docker then other container solutions.  This will also be interesting in years to come because it provides history.
* The last 1/3 of the talk is specifically about current container technology being used for HPC like Shifter, Charliecoud, and Singularity.  This part of the talk with likely age quickly and become irrelevant the most quickly.

My recommendation:  I would say it is worthwhile to provide a curate content article with the proper disclaimer: This talk is for people (like me) who want to understand the underlying foundation for container technology and the security and other major issues that present themselves with containers and that differentiate containers from VMs.   This talk does not provide any info on how to use any particular container solution.

**Comment by bartlettroscoe** [comment]
Hello @pagrubel, is this still on track for late October?

**Comment by pagrubel** [comment]
@bartlettroscoe I'm working on it now and like you will have to go through LANL approval. So hope to have a draft in a few days

**Comment by pagrubel** [comment]
@bartlettroscoe The article is written, but I hit a snag with LANL approval. I hope I can get it cleared up quickly.

**Comment by pagrubel** [comment]
Closing this issue see PR #441
